# Generated by Django 4.2 on 2023-04-24 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('A', 'Adventure'), ('C', 'Classic'), ('CO', 'Comic'), ('D', 'Detective'), ('M', 'Mystery'), ('F', 'Fantasy'), ('H', 'Horror'), ('R', 'Romance'), ('SC', 'Science-Fiction'), ('TH', 'Thriller'), ('B', 'Biographie'), ('TC', 'True-Crime'), ('P', 'Poetry'), ('NF', 'Non-Fiction')], max_length=2)),
                ('pages', models.IntegerField()),
                ('date_published', models.DateField(blank=True, default=datetime.date.today)),
                ('type', models.CharField(choices=[('H', 'Hardcover'), ('P', 'Paperback'), ('E', 'E-book'), ('A', 'Audio book')], max_length=1)),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('book_picture', models.ImageField(blank=True, null=True, upload_to='book_pictures')),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='book_pdfs')),
                ('review_rating', models.IntegerField(default=0)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookUsers', related_query_name='BookUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title', '-type'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('star_rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.review')),
            ],
        ),
    ]
